### ISSUE TITLE
Nice Work

### ISSUE THREAD

**Issue by Gatsby23** [JokerJohn/LIO-SAM-6AXIS-VLOOP#1]
Nice Work~But what is the difference between LIO-SAM-6AXIS-INTENSITY？

**Comment by JokerJohn** [comment]
> Nice Work~But what is the difference between LIO-SAM-6AXIS-INTENSITY？

The intensity image is essentially an image projected by the lidar in scan order, which is a panoramic image scanned in 360 degrees, but with low resolution. For example, 2048*128, 128 represents 128 wiring harnesses. so for lower beams lidar or in outdoors scenerios, the performance of visual loop detection will be poor, such as missed detection or false detection.

for Image from RGB camera,  it has small FOV but high resolution, such as 1024*768. Under normal lighting conditions, the quality of visual loop detection is better.

**Comment by Gatsby23** [comment]
> resolution

OK，I get your point. So this work is using the visual information to do the loop closure constraints. It's more like a LIV-SAM without VIO part？

**Comment by JokerJohn** [comment]
> 

Yes, in order to improve the accuracy of the whole SLAM system, we prefer to introduce the VSLAM module at a small cost, and visual loop detection is a good choice.

**Comment by Gatsby23** [comment]
> > 
> 
> Yes, in order to improve the accuracy of the whole SLAM system, we prefer to introduce the VSLAM module at a small cost, and visual loop detection is a good choice.

Thank you for your patience replay. It's really a nice work
